# Generated by Django 5.2.5 on 2025-09-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiki', '0002_playlist_playlistsong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='total_songs',
        ),
        migrations.AddField(
            model_name='playlist',
            name='tracks',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
    ]
