# Generated by Django 5.2.5 on 2025-09-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hibiki', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
