# Generated by Django 5.2.5 on 2025-10-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiki', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
