# Generated by Django 5.2.5 on 2025-10-02 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiki', '0008_user_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_activity',
        ),
        migrations.CreateModel(
            name='SongPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(max_length=200)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.PositiveIntegerField(help_text='Listened duration in seconds')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_plays', to='hibiki.user')),
            ],
        ),
    ]
