# Generated by Django 5.2.5 on 2025-10-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hibiki', '0009_remove_user_last_activity_songplay'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SongPlay',
        ),
    ]
