# Generated by Django 5.2.5 on 2025-10-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hibiki', '0011_songplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
